config/routes.rb
Scavenge::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  match '/' => 'home#index', :as => :home
  match '/' => 'home#index', :as => :root

  match '/purchase_clue/:clue_id' => 'home#purchase_clue', :as => :purchase_clue, :method => :post

  devise_for :team_members, :controllers => { :sessions => "sessions" }
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/clue.rb
class Clue < ActiveRecord::Base
  belongs_to :question
  has_and_belongs_to_many :solutions

  def to_s; %(#{name} (-#{point_cost})); end

  def as_json(*args)
    {
      :question => question[:name],
      :question_id => question_id,
      :possible_points => question.possible_points,
      :text => text,
      :id => id,
      :point_cost => point_cost
    }
  end
end

app/models/clue_solution.rb
class ClueSolution < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :solutions, :dependent => :destroy
  has_many :clues, :dependent => :destroy

  def email_subject
    self[:id].to_s
  end


  def to_s
    name
  end
end

app/models/score.rb
class Score
  attr_reader :current, :possible, :clues_purchased
  def initialize(collection)
    @collection = collection
    @current = 0
    @possible = 0
    @clues_purchased = 0
    @collection.each do |solution|
      @current += solution.points_awarded
      @possible += solution.possible_points_still_available
      @clues_purchased += solution.points_spent_on_clues
    end
  end

  def <=>(other)
    self.current <=> other.current
  end
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  RESPONSES = ['Accept', 'Reject']
  belongs_to :question
  belongs_to :team
  has_and_belongs_to_many :purchased_clues, :join_table => 'clues_solutions', :class_name => 'Clue'
  mount_uploader :proposed_solution, ProposedSolutionUploader

  delegate :email_subject, :possible_points, :to => :question

  def clues
    return @clues if @clues
    @clues = []
    question.clues.inject(@clues) {|mem, clue|
      clue.singleton_class.send(:attr_writer, :purchased)
      clue.purchased = purchased_clues.include?(clue)
      def clue.purchased?
        !!@purchased
      end
      mem << clue
    }
    @clues
  end

  def possible_points_still_available
    possible_points - points_spent_on_clues
  end

  def points_spent_on_clues
    purchased_clues.sum(:point_cost)
  end

  def to_s
    question.to_s
  end

  def score
    @score ||= Score.new([self])
  end

  attr_reader :response_for_proposed_solution
  def response_for_proposed_solution=(value)
    RESPONSES.each do |response|
      send(response.downcase) if value.to_s.downcase == response.downcase
    end
  end

  def points_awarded
    return 0 unless solved?
    return @points_awarded if defined?(@points_awarded)
    @points_awarded = possible_points - points_spent_on_clues
    @points_awarded = 0 if @points_awarded < 0
    @points_awarded
  end

  def self.purchase_clue(team_member, clue)
    team = team_member.respond_to?(:team) ? team_member.team : TeamMember.include(:team).find(team_member).team
    clue = clue.respond_to?(:question_id) ? clue : Clue.find(clue).includes(:question)
    question = clue.question
    where(:team_id => team[:id]).where(:question_id => question[:id]).first.tap do |solution|
      begin
        solution.purchased_clues << clue unless solution.purchased_clues.include?(clue)
      rescue ActiveRecord::StatementInvalid => e
        true # this was already solved, no worries
      end
    end
    return true
  end

  def self.propose(team_member, possible_question, attachment)
    team = team_member.team
    question = Question.find(possible_question)
    where(:team_id => team[:id]).where(:question_id => question[:id]).first.tap do |solution|
      solution.propose_solution(attachment)
    end
  end

  def propose_solution(attachment)
    Tempfile.new(attachment.filename).tap {|temp|
      temp << attachment.read
      temp.flush
      upload = ActionDispatch::Http::UploadedFile.new(:filename => attachment.filename, :content_type => attachment.content_type, :tempfile => temp)
      self.proposed_solution = upload
    }
    solve!
    save!
  end

  state_machine :state, :initial => :open do
    event :solve do
      transition [:open, :pending] => :pending
    end

    event :accept do
      transition [:rejected, :pending] => :accepted
    end

    event :reject do
      transition [:accepted, :pending] => :rejected
    end

    state :open
    state :pending
    state :accepted
    state :rejected
  end

  def solved?
    !open?
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :solutions, :dependent => :destroy, :include => :question
  has_many :questions, :through => :solutions
  has_many :team_members

  def self.leaderboard
    all.sort {|a,b| a.score <=> b.score }
  end

  def to_s
    name
  end

  def score
    @score ||= Score.new(self.solutions)
  end

  def team
    self
  end
end

app/models/team_member.rb
class TeamMember < User
  belongs_to :team
  validates_presence_of :team_id

  attr_accessible :email, :password, :password_confirmation, :remember_me, :team_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def to_s; email; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'front_side'
  before_filter :authenticate_team_member!, :only => :purchase_clue
  def index
  end

  def purchase_clue
    clue = Clue.find(params[:clue_id])
    if Solution.purchase_clue(current_team_member, clue)
      flash[:notice] = "Clue purchased: #{clue.text}"
      respond_to do |format|
        format.html { redirect_to home_path }
        format.js { clue.to_json }
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  prepend_view_path('app/views/devise')
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dom_class(object, prefix = nil)
    return super(object, prefix) unless object.respond_to?(:purchased?)
    %(#{super(object, prefix)} #{object.purchased? ? 'purchased' : 'available'})
  end
end

app/views/admin/solutions/_form.html.erb
<h2>Current Status: <%= @solution.state_name %></h2>
<%= semantic_form_for [:admin, @solution] do |f| %>
  <%= f.inputs do %>
    <%= f.input :team, :input_html => { :disabled => !f.object.new_record? } %>
    <%= f.input :question, :input_html => { :disabled => !f.object.new_record? } %>
  <% end %>
  <% if f.object.solved? && f.object.proposed_solution?  %>
    <%= f.inputs do %>
      <%= image_tag f.object.proposed_solution.url  %>
      <%= f.input :response_for_proposed_solution, :as => :select, :collection => Solution::RESPONSES %>
    <% end %>
  <% else %>
    <p>Solution has yet to be provided.</p>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/home/_leader_board.html.erb
<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Score</th>
      <th>Possible</th>
      <th>Clues Purchased</th>
      <th>Questions Answered</th>
    </tr>
  </thead>
  <tbody>
    <% Team.leaderboard.each do |team| %>
      <tr>
        <td><%= team %></td>
        <td><%= team.score.current %></td>
        <td><%= team.score.possible %></td>
        <td><%= team.score.clues_purchased %></td>
        <td><%= team.solutions.without_state(:open).count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>Welcome <%= current_team_member %></h1>
<ul data-role="listview">
  <li>
    <%- if team_member_signed_in? -%>
      <%= link_to 'Sign Out', destroy_team_member_session_path %>
    <%- else -%>
      <%= link_to "Sign In", new_team_member_session_path  %>
    <%- end -%>
  </li>
</ul>

<%- if current_team_member -%>
  <h2>Remaining Items</h2>
  <div id="team_solutions">
    <table>
      <thead>
        <tr>
          <th>Subject</th>
          <th>Item</th>
        </tr>
      </thead>
      <tbody>
      <% current_team_member.team.solutions.with_state(:open).each do |solution| %>
        <tr class="<%= cycle('odd','even') %>">
          <td><%= solution.email_subject %></td>
          <td><%= solution.question %> (<%= solution.score.possible %>)
            <ul class="actions">
              <%- solution.clues.each do |clue| -%>
                <li>
                  <%- if clue.purchased? -%>
                    <span class="clue_text"> <%= clue.text %> (-<%= clue.point_cost %> pts)</span>
                  <%- else -%>
                    <%= button_to clue, purchase_clue_path(clue), :method => :post, :confirm => "This will reduce the questions value by #{clue.point_cost}. Are you sure?", :class => "button" %>
                  <%- end -%>
                </li>
              <%- end -%>
            </ul>
          </td>
        </tr>
      <%- end -%>
      </tbody>
    </table>
  </div>
<%- else -%>
  <h2>Items</h2>
  <div id="team_solutions">
    <table>
      <thead>
        <tr>
          <th>Subject</th>
          <th>Item</th>
        </tr>
      </thead>
      <tbody>
      <%- Question.all.each do |question| -%>
        <tr class="<%= cycle('odd','even') %>">
          <td><%= question.email_subject %></td>
          <td><%= question %></td>
        </tr>
      <%- end -%>
      </tbody>
    </table>
  </div>

<%- end -%>

<div id="leader_board">
  <h2>Leader Board</h2>
  <%= render 'leader_board' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scavenge</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/front_side.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scavenge</title>
  <link rel="apple-touch-icon" href="/images/webclip.png">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <%= stylesheet_link_tag    "jquery-mobile", "front_side" %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
  <%= javascript_include_tag "jquery-mobile" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => "shared/jquery_mobile_page_start" %>
    <%= yield %>
<%= render :partial => "shared/jquery_mobile_page_end" %>

</body>
</html>

app/views/shared/_jquery_mobile_page_end.erb
  </div>
</div><!-- /page -->

app/views/shared/_jquery_mobile_page_start.erb
<div data-role="page">
  <div data-role="header">
      <h1>Scavenge</h1>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </div><!-- /header -->
  <div data-role="content">